/*
 * Copyright (C) 2010-2013 Groupement d'Intérêt Public pour l'Education Numérique en Afrique (GIP ENA)
 *
 * This file is part of Open-Sankoré.
 *
 * Open-Sankoré is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3 of the License,
 * with a specific linking exception for the OpenSSL project's
 * "OpenSSL" library (or with modified versions of it that use the
 * same license as the "OpenSSL" library).
 *
 * Open-Sankoré is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Open-Sankoré.  If not, see <http://www.gnu.org/licenses/>.
 */



#include <QWidget>
#include <QApplication>
#include <QPainter>
#include <QTimer>
#include <cstdio>
#include <string>
#ifdef _WIN32
#include <windows.h>
#include <dbghelp.h>
#pragma comment(lib, "dbghelp.lib")
#else
#include <signal.h>
#endif

// Git version (generated by CI)
#if __has_include("git_version.h")
#include "git_version.h"
#endif
#ifndef GIT_COMMIT
#define GIT_COMMIT "local"
#endif

// === CRASH HANDLER (Windows SEH) ===
#ifdef _WIN32
LONG WINAPI CrashHandler(EXCEPTION_POINTERS* pExceptionInfo)
{
    // Open startup.log next to the exe
    wchar_t exePath[MAX_PATH];
    GetModuleFileNameW(NULL, exePath, MAX_PATH);
    std::wstring logPath(exePath);
    size_t lastSlash = logPath.find_last_of(L"\\/");
    if (lastSlash != std::wstring::npos) logPath = logPath.substr(0, lastSlash + 1);
    logPath += L"startup.log";
    FILE *f = _wfopen(logPath.c_str(), L"a");

    if (f) {
        fprintf(f, "\n=== CRASH DETECTED ===\n");
        fprintf(f, "Exception code: 0x%08lX\n", pExceptionInfo->ExceptionRecord->ExceptionCode);
        fprintf(f, "Exception address: 0x%p\n", pExceptionInfo->ExceptionRecord->ExceptionAddress);
        fprintf(f, "RIP: 0x%016llX\n", pExceptionInfo->ContextRecord->Rip);

        // Walk the stack
        fprintf(f, "Stack trace:\n");
        HANDLE process = GetCurrentProcess();
        HANDLE thread = GetCurrentThread();
        SymInitialize(process, NULL, TRUE);

        STACKFRAME64 frame = {};
        frame.AddrPC.Offset = pExceptionInfo->ContextRecord->Rip;
        frame.AddrPC.Mode = AddrModeFlat;
        frame.AddrFrame.Offset = pExceptionInfo->ContextRecord->Rbp;
        frame.AddrFrame.Mode = AddrModeFlat;
        frame.AddrStack.Offset = pExceptionInfo->ContextRecord->Rsp;
        frame.AddrStack.Mode = AddrModeFlat;

        for (int i = 0; i < 20; i++) {
            if (!StackWalk64(IMAGE_FILE_MACHINE_AMD64, process, thread, &frame,
                            pExceptionInfo->ContextRecord, NULL,
                            SymFunctionTableAccess64, SymGetModuleBase64, NULL))
                break;

            DWORD64 addr = frame.AddrPC.Offset;
            char symbolBuffer[sizeof(SYMBOL_INFO) + 256];
            SYMBOL_INFO* symbol = (SYMBOL_INFO*)symbolBuffer;
            symbol->SizeOfStruct = sizeof(SYMBOL_INFO);
            symbol->MaxNameLen = 255;

            if (SymFromAddr(process, addr, NULL, symbol)) {
                fprintf(f, "  [%d] %s + 0x%llX (0x%016llX)\n", i, symbol->Name, addr - symbol->Address, addr);
            } else {
                fprintf(f, "  [%d] 0x%016llX\n", i, addr);
            }
        }

        SymCleanup(process);
        fprintf(f, "=== END CRASH ===\n");
        fflush(f);
        fclose(f);
    }
    return EXCEPTION_EXECUTE_HANDLER;
}
#endif

// Static initializer that runs BEFORE main() to detect pre-main crashes
#ifdef _WIN32
struct StartupProbe {
    StartupProbe() {
        wchar_t exePath[MAX_PATH];
        GetModuleFileNameW(NULL, exePath, MAX_PATH);
        std::wstring logPath(exePath);
        size_t lastSlash = logPath.find_last_of(L"\\/");
        if (lastSlash != std::wstring::npos) logPath = logPath.substr(0, lastSlash + 1);
        logPath += L"startup.log";
        FILE *f = _wfopen(logPath.c_str(), L"w");
        if (f) {
            fprintf(f, "=== Open-Sankore Startup Log ===\n");
            fprintf(f, "Build: %s (compiled %s %s)\n", GIT_COMMIT, __DATE__, __TIME__);
            fprintf(f, "PRE-MAIN: Static initialization reached\n");
            fflush(f);
            fclose(f);
        }
    }
};
static StartupProbe _startupProbe;
#endif

// === UNIX SIGNAL HANDLER (coverage flush + clean exit) ===
#ifndef _WIN32
// GCC coverage flush — ensure .gcda files are written on signal
extern "C" void __gcov_dump(void) __attribute__((weak));

static void unixSignalHandler(int sig)
{
    Q_UNUSED(sig);
    // Flush gcov data if compiled with --coverage
    if (__gcov_dump)
        __gcov_dump();
    // Exit cleanly so atexit handlers also run
    _exit(0);
}
#endif

#include "frameworks/UBPlatformUtils.h"
#include "frameworks/UBFileSystemUtils.h"

#include "UBApplication.h"
#include "UBSettings.h"
#include "board/UBBoardController.h"

/* Uncomment this for memory leaks detection */
/*
#if defined(WIN32) && defined(_DEBUG)
     #define _CRTDBG_MAP_ALLOC
     #include <stdlib.h>
     #include <crtdbg.h>
     #define DEBUG_NEW new( _NORMAL_BLOCK, __FILE__, __LINE__ )
     #define new DEBUG_NEW
#endif
*/

void ub_message_output(QtMsgType type, const QMessageLogContext &context, const QString &msg) {
    Q_UNUSED(context);

#if defined(QT_NO_DEBUG)
    // Suppress qDebug output in release builds
    if (type != QtDebugMsg)
    {
        fprintf(stderr, "%s\n", qPrintable(msg));
    }
#else
    // Default output in debug builds
    fprintf(stderr, "%s\n", qPrintable(msg));
#endif

    if (UBApplication::app() && UBApplication::app()->isVerbose()) {
        QString logFileNamePath = UBSettings::userDataDirectory() + "/log/uniboard.log";
        QFile logFile(logFileNamePath);

        if (logFile.exists() && logFile.size() > 10000000)
            logFile.remove();

        if (logFile.open(QIODevice::Append | QIODevice::Text)) {
            QTextStream out(&logFile);
            out << QDateTime::currentDateTime().toString(Qt::ISODate)
                << "      " << msg << "\n";
            logFile.close();
        }
    }
}

int main(int argc, char *argv[]) 
{

    // Uncomment next section to have memory leaks information
    // tracing in VC++ debug mode under Windows
/*
#if defined(_MSC_VER) && defined(_DEBUG)
    _CrtSetDbgFlag ( _CRTDBG_ALLOC_MEM_DF | _CRTDBG_LEAK_CHECK_DF );
#endif
*/

    // === STARTUP CRASH HANDLER ===
    {
#ifdef _WIN32
        // Install crash handler FIRST
        SetUnhandledExceptionFilter(CrashHandler);
#else
        // Install Unix signal handlers for clean shutdown + gcov flush
        signal(SIGINT, unixSignalHandler);
        signal(SIGTERM, unixSignalHandler);
#endif
    }

    Q_INIT_RESOURCE(sankore);

    qInstallMessageHandler(ub_message_output);

    UBApplication app("Sankore", argc, argv);

    QStringList args = app.arguments();

    // --quit-after=N : automatically quit after N seconds (for CI smoke tests / coverage)
    int quitAfterSec = 0;
    bool smokeScenario = false;
    for (const QString &arg : args) {
        if (arg.startsWith("--quit-after=")) {
            quitAfterSec = arg.mid(13).toInt();
        }
        if (arg == "--smoke-scenario") {
            smokeScenario = true;
        }
    }
    if (quitAfterSec > 0) {
        QTimer::singleShot(quitAfterSec * 1000, &app, &QCoreApplication::quit);
        qDebug() << "CI mode: will auto-quit after" << quitAfterSec << "seconds";
    }

    QString dumpPath = UBSettings::userDataDirectory() + "/log";
    QDir logDir(dumpPath);
    if (!logDir.exists())
        logDir.mkdir(dumpPath);

    QString fileToOpen;

      if (args.size() > 1) {
        // On Windows/Linux first argument is the file that has been double clicked.
        // On Mac OSX we use FileOpen QEvent to manage opening file in current instance. So we will never
        // have file to open as a parameter on OSX.

        for (int i = 1; i < args.size(); i++) {
            if (args[i].startsWith("--"))
                continue;
            QFile f(args[i]);
            if (f.exists()) {
                fileToOpen = args[i];
                break;
            }
        }
    }

    //Hotfix. We allways have the single instance application independent from number of parameters
    if (app.sendMessage(UBSettings::appPingMessage, 20000)) {
        if (!fileToOpen.isNull()) {
            app.sendMessage(fileToOpen, 1000000);
        }
        return 0;
    }

    // app.initialize(false); -- initialization handled in exec()

    QObject::connect(&app, &QtSingleApplication::messageReceived, &app, &UBApplication::handleOpenMessage);

    qDebug() << "file name argument" << fileToOpen;

    // CI smoke scenario: exercise core features after startup
    if (smokeScenario) {
        QTimer::singleShot(2000, [&]() {
            qDebug() << "=== Smoke scenario: starting ===";
            if (UBApplication::boardController) {
                auto *bc = UBApplication::boardController;
                qDebug() << "Smoke: addScene";
                bc->addScene();
                qDebug() << "Smoke: addScene (2)";
                bc->addScene();
                qDebug() << "Smoke: previousScene";
                bc->previousScene();
                qDebug() << "Smoke: nextScene";
                bc->nextScene();
                qDebug() << "Smoke: zoomIn";
                bc->zoomIn();
                qDebug() << "Smoke: zoomOut";
                bc->zoomOut();
                qDebug() << "Smoke: changeBackground(dark, crossed)";
                bc->changeBackground(true, true);
                qDebug() << "Smoke: changeBackground(light, plain)";
                bc->changeBackground(false, false);
                qDebug() << "Smoke: clearScene";
                bc->clearScene();
                qDebug() << "Smoke: duplicateScene";
                bc->duplicateScene();
                qDebug() << "Smoke: deleteScene(1)";
                bc->deleteScene(1);
                qDebug() << "Smoke: persistCurrentScene";
                bc->persistCurrentScene();
                qDebug() << "Smoke: firstScene";
                bc->firstScene();
                qDebug() << "Smoke: lastScene";
                bc->lastScene();
                qDebug() << "=== Smoke scenario: done ===";
            } else {
                qDebug() << "Smoke: boardController is null, skipping";
            }
        });
    }

    int result = app.exec(fileToOpen);

    app.cleanup();

    qDebug() << "application is quitting";



    return result;

}
