/*
 * Copyright (C) 2010-2013 Groupement d'Intérêt Public pour l'Education Numérique en Afrique (GIP ENA)
 *
 * This file is part of Open-Sankoré.
 *
 * Open-Sankoré is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3 of the License,
 * with a specific linking exception for the OpenSSL project's
 * "OpenSSL" library (or with modified versions of it that use the
 * same license as the "OpenSSL" library).
 *
 * Open-Sankoré is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Open-Sankoré.  If not, see <http://www.gnu.org/licenses/>.
 */



#include <QWidget>
#include <QApplication>
#include <QPainter>
#include <cstdio>
#include <string>
#ifdef _WIN32
#include <windows.h>
#endif

// Git version (generated by CI)
#if __has_include("git_version.h")
#include "git_version.h"
#endif
#ifndef GIT_COMMIT
#define GIT_COMMIT "local"
#endif

// Static initializer that runs BEFORE main() to detect pre-main crashes
#ifdef _WIN32
struct StartupProbe {
    StartupProbe() {
        wchar_t exePath[MAX_PATH];
        GetModuleFileNameW(NULL, exePath, MAX_PATH);
        std::wstring logPath(exePath);
        size_t lastSlash = logPath.find_last_of(L"\\/");
        if (lastSlash != std::wstring::npos) logPath = logPath.substr(0, lastSlash + 1);
        logPath += L"startup.log";
        FILE *f = _wfopen(logPath.c_str(), L"w");
        if (f) {
            fprintf(f, "=== Open-Sankore Startup Log ===\n");
            fprintf(f, "Build: %s (compiled %s %s)\n", GIT_COMMIT, __DATE__, __TIME__);
            fprintf(f, "PRE-MAIN: Static initialization reached\n");
            fflush(f);
            fclose(f);
        }
    }
};
static StartupProbe _startupProbe;
#endif

#include "frameworks/UBPlatformUtils.h"
#include "frameworks/UBFileSystemUtils.h"

#include "UBApplication.h"
#include "UBSettings.h"

/* Uncomment this for memory leaks detection */
/*
#if defined(WIN32) && defined(_DEBUG)
     #define _CRTDBG_MAP_ALLOC
     #include <stdlib.h>
     #include <crtdbg.h>
     #define DEBUG_NEW new( _NORMAL_BLOCK, __FILE__, __LINE__ )
     #define new DEBUG_NEW
#endif
*/

void ub_message_output(QtMsgType type, const QMessageLogContext &context, const QString &msg) {
    Q_UNUSED(context);

#if defined(QT_NO_DEBUG)
    // Suppress qDebug output in release builds
    if (type != QtDebugMsg)
    {
        fprintf(stderr, "%s\n", qPrintable(msg));
    }
#else
    // Default output in debug builds
    fprintf(stderr, "%s\n", qPrintable(msg));
#endif

    if (UBApplication::app() && UBApplication::app()->isVerbose()) {
        QString logFileNamePath = UBSettings::userDataDirectory() + "/log/uniboard.log";
        QFile logFile(logFileNamePath);

        if (logFile.exists() && logFile.size() > 10000000)
            logFile.remove();

        if (logFile.open(QIODevice::Append | QIODevice::Text)) {
            QTextStream out(&logFile);
            out << QDateTime::currentDateTime().toString(Qt::ISODate)
                << "      " << msg << "\n";
            logFile.close();
        }
    }
}

int main(int argc, char *argv[]) 
{

    // Uncomment next section to have memory leaks information
    // tracing in VC++ debug mode under Windows
/*
#if defined(_MSC_VER) && defined(_DEBUG)
    _CrtSetDbgFlag ( _CRTDBG_ALLOC_MEM_DF | _CRTDBG_LEAK_CHECK_DF );
#endif
*/

    // === STARTUP DIAGNOSTIC LOG ===
    // Write to a file next to the exe to diagnose crashes
    // Use GetModuleFileName to get absolute path (works even on network drives)
    {
#ifdef _WIN32
        wchar_t exePath[MAX_PATH];
        GetModuleFileNameW(NULL, exePath, MAX_PATH);
        std::wstring logPath(exePath);
        size_t lastSlash = logPath.find_last_of(L"\\/");
        if (lastSlash != std::wstring::npos) logPath = logPath.substr(0, lastSlash + 1);
        logPath += L"startup.log";
        FILE *f = _wfopen(logPath.c_str(), L"w");
        if (f) {
            fprintf(f, "=== Open-Sankore Startup Log ===\n");
            fprintf(f, "Step 0: main() entered OK\n");
            fprintf(f, "argc=%d\n", argc);
            fflush(f);
            fclose(f);
        }
#endif
    }

    Q_INIT_RESOURCE(sankore);

    qInstallMessageHandler(ub_message_output);

    // Log step 1
    { FILE *f = fopen("startup.log", "a"); if(f){fprintf(f,"Step 1: QApplication creating\n");fclose(f);} }

    UBApplication app("Sankore", argc, argv);

    // Log step 2
    { FILE *f = fopen("startup.log", "a"); if(f){fprintf(f,"Step 2: UBApplication created\n");fclose(f);} }

    QStringList args = app.arguments();

    QString dumpPath = UBSettings::userDataDirectory() + "/log";
    QDir logDir(dumpPath);
    if (!logDir.exists())
        logDir.mkdir(dumpPath);

    QString fileToOpen;

      if (args.size() > 1) {
        // On Windows/Linux first argument is the file that has been double clicked.
        // On Mac OSX we use FileOpen QEvent to manage opening file in current instance. So we will never
        // have file to open as a parameter on OSX.

        QFile f(args[1]);

        if (f.exists()) {
            fileToOpen += args[1];
        }
    }

    //Hotfix. We allways have the single instance application independent from number of parameters
    if (app.sendMessage(UBSettings::appPingMessage, 20000)) {
        if (!fileToOpen.isNull()) {
            app.sendMessage(fileToOpen, 1000000);
        }
        return 0;
    }

    // app.initialize(false); -- initialization handled in exec()

    QObject::connect(&app, &QtSingleApplication::messageReceived, &app, &UBApplication::handleOpenMessage);

    qDebug() << "file name argument" << fileToOpen;

    // Log step 3
    { FILE *f = fopen("startup.log", "a"); if(f){fprintf(f,"Step 3: calling app.exec()\n");fclose(f);} }

    int result = app.exec(fileToOpen);

    app.cleanup();

    qDebug() << "application is quitting";



    return result;

}
